export { LoggerService } from 'Core/services/LoggerService/LoggerService'
export { ComponentsService } from 'Core/services/ComponentsService/ComponentsService'
export { AssetsDownloadService } from 'Core/services/AssetsDownloadService/AssetsDownloadService'
export { MachineSubscriptionService } from 'Core/services/MachineSubscriptionService/MachineSubscriptionService'
export { Animation } from 'Core/services/AnimationService/Animation'
export { OrientationChangeService } from 'Core/services/OrientationChangeService/OrientationChangeService'
export { SoundService } from 'Core/services/SoundService/SoundService'
// export { RemoveBlackShaderService } from 'Core/services/RemoveBlackShader/RemoveBlackShaderService'
export { FooterComponentsService } from 'Core/services/FooterComponentsService/FooterComponentService'
export { SlotMachineComponentsService } from 'Core/services/SlotMachineComponentsService/SlotMachineComponentsService'
export { LayoutService } from 'Core/services/LayoutService/LayoutService'
export { TranslationService } from 'Core/services/TranslationService/TranslationService'
