const IoCContainerTypes = {
  // services
  LoggerService: Symbol.for('LoggerService'),
  AssetsDownloadService: Symbol.for('AssetsDownloadService'),
  MachineSubscriptionService: Symbol.for('MachineSubscriptionService'),
  LayoutService: Symbol.for('LayoutService'),
  ComponentsService: Symbol.for('ComponentsService'),
  SoundService: Symbol.for('SoundService'),
  FooterComponentsService: Symbol.for('FooterComponentsService'),
  SlotMachineComponentsService: Symbol.for('SlotMachineComponentsService'),
  TranslationService: Symbol.for('TranslationService'),

  // constants
  AppConfig: Symbol.for('AppConfig'),

  // containers
  Footer: Symbol.for('Footer'),
  SlotMachineContainer: Symbol.for('SlotMachineContainer'),
  ModalContainer: Symbol.for('ModalContainer'),

  // components
  Stage: Symbol.for('Stage'),
  GameBg: Symbol.for('GameBg'),
  Loader: Symbol.for('Loader'),
  Reels: Symbol.for('Reels'),
  ReelsBg: Symbol.for('ReelsBg'),
  TrailSymbols: Symbol.for('TrailSymbols'),
  GameTitle: Symbol.for('GameTitle'),
  TumbleWin: Symbol.for('TumbleWin'),
  GameTitleWinSpin: Symbol.for('GameTitleWinSpin'),
  SpinButton: Symbol.for('SpinButton'),
  Sound: Symbol.for('Sound'),
  IntroScreen: Symbol.for('IntroScreen'),
  IntroScreenReels: Symbol.for('IntroScreenReels'),
  Settings: Symbol.for('Settings'),
  Clouds: Symbol.for('Clouds'),
  GameContainer: Symbol.for('GameContainer'),
  BgAnimation: Symbol.for('BgAnimation'),
  GameCharacter: Symbol.for('GameCharacter'),
  AdditionalCharacter: Symbol.for('AdditionalCharacter'),
  SideMenu: Symbol.for('SideMenu'),
  BettingCalculator: Symbol.for('BettingCalculator'),
  GameText: Symbol.for('GameText'),
  AutoPlay: Symbol.for('AutoPlay'),
  Balance: Symbol.for('Balance'),
  DoubleChance: Symbol.for('DoubleChance'),
  Rules: Symbol.for('Rules'),
  Replays: Symbol.for('Replays'),
  Tournaments: Symbol.for('Tournaments'),
  DailyTournament: Symbol.for('DailyTournament'),
  DropsAndWinsModal: Symbol.for('DropsAndWinsModal'),
  HolidayModal: Symbol.for('HolidayModal'),
  ErrorModal: Symbol.for('ErrorModal'),
  FreeSpinCongratulations: Symbol.for('FreeSpinCongratulations'),
  FreeRoundsModal: Symbol.for('FreeRoundsModal'),
  FreeRounds: Symbol.for('FreeRounds'),
  GameHistory: Symbol.for('GameHistory'),
  ShareReplay: Symbol.for('ShareReplay'),
  JackpotModal: Symbol.for('JackpotModal'),
  JackpotModalHeaderTitle: Symbol.for('JackpotModalHeaderTitle'),
  JackpotModalUI: Symbol.for('JackpotModalUI'),
  JackpotModalHeaderStarsUI: Symbol.for('JackpotModalHeaderStarsUI'),
  JackpotModalHeaderShineUI: Symbol.for('JackpotModalHeaderShineUI'),
  JackpotModalDigitsCounterUI: Symbol.for('JackpotModalDigitsCounterUI'),
  JackpotModalTotalUI: Symbol.for('JackpotModalTotalUI'),
  JackpotModalCoinsAnimation: Symbol.for('JackpotModalCoinsAnimation'),
  LowBalanceModal: Symbol.for('LowBalanceModal'),
  DebugViewer: Symbol.for('DebugViewer'),
  FastPlayHintModal: Symbol.for('FastPlayHintModal'),
  FreeSpinsTransition: Symbol.for('FreeSpinsTransition'),
  FreeSpinStarBgAnimation: Symbol.for('FreeSpinStarBgAnimation'),
  BuyFeature: Symbol.for('BuyFeature'),
  BuyFeatureModal: Symbol.for('BuyFeatureModal'),
  BuySuperFeatureModal: Symbol.for('BuySuperFeatureModal'),
  ReplayText: Symbol.for('ReplayText'),
  Clock: Symbol.for('Clock'),
  ProductionLogo: Symbol.for('ProductionLogo'),
  FreeSpinsMoreModal: Symbol.for('FreeSpinsMoreModal'),
  WinningsPerSpin: Symbol.for('WinningsPerSpin'),
  FreeSpinsLeft: Symbol.for('FreeSpinsLeft'),
  FreeSpinsTotalMultiplier: Symbol.for('FreeSpinsTotalMultiplier'),
  SoundsSubscriber: Symbol.for('SoundsSubscriber'),
  IntroBgAnimation: Symbol.for('IntroBgAnimation'),

  // candy
  FastPlayHintModalCandyWindfall: Symbol.for('FastPlayHintModalCandyWindfall'),

  // constants
  ComponentsCollection: Symbol.for('ComponentsCollection'),
  FooterCollection: Symbol.for('FooterCollection'),
  SlotMachineCollection: Symbol.for('SlotMachineCollection'),
}

export { IoCContainerTypes }
